getKanjiJson = () => {
    return [
        { "syllable": "आ", "char": "imgs/a-k.PNG" },
        { "syllable": "ई", "char": "imgs/i-k.PNG" },
        { "syllable": "ऊ", "char": "imgs/u-k.PNG" },
        { "syllable": "ए", "char": "imgs/e-k.PNG" },
        { "syllable": "ओ", "char": "imgs/o-k.PNG" },
        { "syllable": "का", "char": "imgs/ka-k.PNG" },
        { "syllable": "की", "char": "imgs/ki-k.PNG" },
        { "syllable": "कू", "char": "imgs/ku-k.PNG" },
        { "syllable": "के", "char": "imgs/ke-k.PNG" },
        { "syllable": "को", "char": "imgs/ko-k.PNG" },
        { "syllable": "सा", "char": "imgs/sa-k.PNG" },
        { "syllable": "शी", "char": "imgs/shi-k.PNG" },
        { "syllable": "सू", "char": "imgs/su-k.PNG" },
        { "syllable": "से", "char": "imgs/se-k.PNG" },
        { "syllable": "सो", "char": "imgs/so-k.PNG" },
        { "syllable": "ता", "char": "imgs/ta-k.PNG" },
        { "syllable": "ची", "char": "imgs/chi-k.PNG" },
        { "syllable": "त्सु", "char": "imgs/tsu-k.PNG" },
        { "syllable": "ते", "char": "imgs/te-k.PNG" },
        { "syllable": "तो", "char": "imgs/to-k.PNG" },
        { "syllable": "ना", "char": "imgs/na-k.PNG" },
        { "syllable": "नी", "char": "imgs/ni-k.PNG" },
        { "syllable": "नू", "char": "imgs/nu-k.PNG" },
        { "syllable": "ने", "char": "imgs/ne-k.PNG" },
        { "syllable": "नो", "char": "imgs/no-k.PNG" },
        { "syllable": "हा", "char": "imgs/ha-k.PNG" },
        { "syllable": "ही", "char": "imgs/hi-k.PNG" },
        { "syllable": "फू", "char": "imgs/fu-k.PNG" },
        { "syllable": "हे", "char": "imgs/he-k.PNG" },
        { "syllable": "हो", "char": "imgs/ho-k.PNG" },
        { "syllable": "मा", "char": "imgs/ma-k.PNG" },
        { "syllable": "मी", "char": "imgs/mi-k.PNG" },
        { "syllable": "मू", "char": "imgs/mu-k.PNG" },
        { "syllable": "मे", "char": "imgs/me-k.PNG" },
        { "syllable": "मो", "char": "imgs/mo-k.PNG" },
        { "syllable": "या", "char": "imgs/ya-k.PNG" },
        { "syllable": "यू", "char": "imgs/yu-k.PNG" },
        { "syllable": "यो", "char": "imgs/yo-k.PNG" },
        { "syllable": "रा", "char": "imgs/ra-k.PNG" },
        { "syllable": "री", "char": "imgs/ri-k.PNG" },
        { "syllable": "रू", "char": "imgs/ru-k.PNG" },
        { "syllable": "रे", "char": "imgs/re-k.PNG" },
        { "syllable": "रो", "char": "imgs/ro-k.PNG" },
        { "syllable": "वा", "char": "imgs/wa-k.PNG" },
        { "syllable": "वी", "char": "imgs/wi-k.PNG" },
        { "syllable": "वे", "char": "imgs/we-k.PNG" },
        { "syllable": "वो", "char": "imgs/wo-k.PNG" },
        { "syllable": "न", "char": "imgs/n-k.PNG" }
    ];
}

